#spring.redis.url: redis://user:password@localhost:6379
server.port: 9030
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
---
spring:
  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/achilles?useSSL=false&serverTimezone=Asia/Shanghai
#    username: demo_user
#    password: demo_password
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: prod
  redis.url: redis://redis:6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/example?useSSL=false
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/