server.port: 9010
supoort-api.url: http://support-api
content-api.url: http://content-api
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/